# Generated by Django 2.2.24 on 2021-09-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post2',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post2',
            name='text2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
